
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[348] =
    {   0,
        2,    2,    0,    0,  113,  111,    2,    1,   99,  111,
      111,  105,   98,  111,   93,   94,  103,  102,   90,  101,
       97,  104,   59,   59,   91,   87,  106,   92,  107,  110,
       56,   95,   96,  108,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   88,  109,   89,  100,  112,  112,  112,    2,   86,
        0,   64,    0,    0,   71,   81,   72,    0,    0,   69,
       77,   67,   78,   68,   79,   62,    0,    0,   70,   63,
       58,   59,    0,   59,    0,   76,   83,   85,   84,   75,
       56,   73,   56,   56,   56,   56,   56,   56,   56,   56,

       25,   56,   56,   56,   56,   56,   56,   33,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   74,   82,    0,    0,    0,    0,
        0,    0,   60,   80,    0,   62,    0,    0,    0,    3,
       62,    0,   63,   58,    0,   61,   57,   66,   65,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   31,   56,   34,   56,   36,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   14,    0,    0,
        0,    0,    0,    0,    0,    0,   62,    4,    0,   62,

        0,   63,   61,   57,   15,   16,   56,   18,   19,   56,
       56,   56,   56,   56,   56,   27,   28,   56,   56,   32,
       35,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   50,   51,   56,   56,   56,   53,   56,   56,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   62,
       17,   20,   21,   56,   56,   56,   56,   56,   30,   56,
       56,   56,   56,   56,   42,   56,   56,   56,   56,   56,
       56,   49,   56,   56,   55,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   56,   56,   24,   26,   29,   56,
       56,   39,   56,   41,   43,   44,   45,   46,   47,   56,

       56,   56,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   56,   23,   37,   56,   56,   48,   56,   56,   12,
        0,    0,   11,    0,    0,    0,    0,    5,   22,   56,
       40,   52,   54,    0,    0,    0,    0,    0,   10,   38,
        8,    9,    7,   13,    0,    6,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   30,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    5,
        5,    5,    5,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[356] =
    {   0,
        0,    0,   61,   62,  491,  492,   66,   68,  466,   67,
      443,  464,   65,  452,  492,  492,  462,   62,  492,   63,
       61,   79,   88,   64,  492,  492,   53,  461,   68,  492,
        0,  492,  492,  460,  427,   47,   67,   48,   63,   66,
      431,   51,  430,  438,   71,  437,   80,   86,  428,  426,
      431,  492,   71,  492,  492,  492,    0,   97,  107,  492,
      123,  492,  472,  424,  492,  492,  492,  120,  139,  492,
      492,  492,  492,  492,  461,  134,  460,  468,  492,  141,
      174,    0,  160,  492,    0,  446,  492,  492,  492,  445,
        0,  492,  413,  416,  424,  411,  426,  425,  412,  102,

      405,  406,  403,  403,  406,  403,  400,    0,  399,  403,
      394,  120,  412,  112,  399,   88,  143,  403,  402,  391,
      394,   87,  139,  399,  492,  492,  439,  146,  389,  391,
      386,  400,  492,  492,  194,  492,  427,  174,  435,  492,
      200,  219,  492,  492,  179,  226,  179,  492,  492,  386,
      388,  397,  392,  380,  378,  149,  393,  388,  390,  386,
      378,  384,  387,    0,  373,    0,  379,    0,  365,  366,
      372,  373,  362,  364,  366,  373,  359,  357,  357,  357,
      368,  367,  357,  361,  365,  367,  356,  492,  365,  347,
      355,  345,  172,  346,  350,  205,  232,  492,  247,  492,

      252,  258,  492,  492,    0,    0,  350,    0,    0,  342,
      340,  348,  337,  337,  343,    0,    0,  337,  334,    0,
        0,  350,  345,  340,  331,  331,  328,  340,  330,  334,
      339,  338,    0,    0,  336,  326,  331,    0,  319,  331,
      317,  200,  322,  317,  331,  313,  321,  310,  263,  266,
        0,    0,    0,  315,  316,  321,  320,  311,    0,  305,
      319,  318,  302,  306,    0,  314,  311,  313,  297,  306,
      308,    0,  299,  302,    0,  302,  285,  281,  271,  270,
      261,  257,  258,  266,  249,  249,    0,    0,    0,  261,
      247,    0,  258,    0,    0,    0,    0,    0,    0,  256,

      256,  248,  269,  247,  242,  266,  252,  242,  237,  229,
      226,  222,    0,    0,  217,  205,    0,  215,  212,  492,
      210,  203,  492,  191,  184,  195,  192,  492,    0,  174,
        0,    0,    0,  183,  163,  149,  143,  115,  492,    0,
      492,  492,  492,  492,  132,  492,  492,  314,  319,  324,
      326,  331,  336,  341,   70
    } ;

static yyconst flex_int16_t yy_def[356] =
    {   0,
      347,    1,  348,  348,  347,  347,  347,  347,  347,  349,
      347,  347,  347,  350,  347,  347,  347,  347,  347,  347,
      347,  347,  347,   23,  347,  347,  347,  347,  347,  347,
      351,  347,  347,  347,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  347,  347,  347,  347,  347,  352,  347,  347,  347,
      349,  347,  349,  347,  347,  347,  347,  350,  350,  347,
      347,  347,  347,  347,  347,  347,  353,  354,  347,  347,
      347,   24,  347,  347,  355,  347,  347,  347,  347,  347,
      351,  347,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  347,  347,  352,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  353,  353,  354,  347,
      347,  347,  347,  347,  347,  347,  355,  347,  347,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  351,  351,  351,  351,  351,  351,  351,  351,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  351,  351,
      351,  351,  351,  347,  347,  347,  347,  347,  347,  351,
      347,  347,  347,  347,  347,  347,    0,  347,  347,  347,
      347,  347,  347,  347,  347
    } ;

static yyconst flex_int16_t yy_nxt[558] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   24,
       25,   26,   27,   28,   29,   30,   31,   31,   31,   31,
       31,   31,   31,   32,    6,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   31,   42,   31,   43,   31,   44,
       31,   45,   46,   47,   48,   49,   50,   51,   31,   31,
       31,   52,   53,   54,   55,   57,   57,   59,   59,   59,
       59,   62,   66,  147,   71,   86,   87,   73,   76,   76,
       76,   82,   82,   58,   58,   72,   74,   75,   67,  100,
       77,   89,   90,  108,  125,   78,  347,   94,  101,   95,

      109,   63,   79,   80,   96,   81,   81,   82,   59,   59,
      102,   97,  103,  105,   98,   83,  106,   99,   84,   84,
       85,  104,  347,  112,  115,  116,  113,   62,  133,   83,
      119,  175,  183,  126,  117,   84,  128,  118,  120,  129,
      184,  347,  130,   84,  157,  121,   85,   68,  176,  158,
      131,   76,   76,   76,   69,  172,  346,   63,  141,  141,
      141,  135,  136,  345,  136,  169,  173,  344,  142,  143,
      170,  143,  145,  343,  145,  135,  136,  146,  146,  146,
      177,  136,  142,  143,  185,  138,  186,  342,  143,   80,
      198,   81,   81,   82,  189,  178,  146,  146,  146,  190,

      191,   83,  211,  212,  144,  144,  196,  341,  196,  204,
      204,  197,  197,  197,  340,   83,  339,  141,  141,  141,
      245,  144,  197,  197,  197,  246,  204,  199,  200,  144,
      200,  201,  338,  201,  204,  337,  202,  202,  202,  336,
      277,  199,  200,  146,  146,  146,  335,  200,  334,  197,
      197,  197,  278,  333,  203,  332,  203,  331,  330,  249,
      136,  249,  136,  329,  250,  250,  250,  328,  203,  202,
      202,  202,  327,  203,  136,  202,  202,  202,  326,  136,
      250,  250,  250,  250,  250,  250,  143,  325,  143,  324,
      323,  322,  321,  320,  200,  319,  200,  318,  317,  316,

      143,  315,  314,  313,  312,  143,  311,  310,  200,  309,
      308,  307,  306,  200,   56,   56,   56,   56,   56,   61,
       61,   61,   61,   61,   68,   68,  305,   68,   68,   91,
       91,  127,  304,  127,  127,  127,  137,  137,  137,  137,
      137,  139,  139,  139,  139,  139,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  248,  247,  244,

      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  210,  209,  208,  207,  206,  205,  140,  138,  195,
      194,  193,  192,  188,  187,  182,  181,  180,  179,  174,
      171,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      140,  138,  134,  132,  347,  124,  123,  122,  114,  111,
      110,  107,   93,   92,   88,   70,   69,   65,   64,   60,
      347,    5,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347
    } ;

static yyconst flex_int16_t yy_chk[558] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    7,    7,    8,
        8,   10,   13,  355,   18,   27,   27,   20,   21,   21,
       21,   24,   24,    3,    4,   18,   20,   20,   13,   38,
       22,   29,   29,   42,   53,   22,   24,   36,   38,   36,

       42,   10,   22,   23,   37,   23,   23,   23,   59,   59,
       39,   37,   39,   40,   37,   23,   40,   37,   23,   23,
       23,   39,   24,   45,   47,   47,   45,   61,   68,   23,
       48,  116,  122,   53,   47,   23,   58,   47,   48,   58,
      122,   69,   58,   23,  100,   48,   23,   69,  116,  100,
       58,   76,   76,   76,   68,  114,  345,   61,   80,   80,
       80,   76,   76,  338,   76,  112,  114,  337,   80,   80,
      112,   80,   83,  336,   83,   76,   76,   83,   83,   83,
      117,   76,   80,   80,  123,  138,  123,  335,   80,   81,
      138,   81,   81,   81,  128,  117,  145,  145,  145,  128,

      128,   81,  156,  156,   81,   81,  135,  334,  135,  147,
      147,  135,  135,  135,  330,   81,  327,  141,  141,  141,
      193,   81,  196,  196,  196,  193,  147,  141,  141,   81,
      141,  142,  326,  142,  147,  325,  142,  142,  142,  324,
      242,  141,  141,  146,  146,  146,  322,  141,  321,  197,
      197,  197,  242,  319,  146,  318,  146,  316,  315,  199,
      197,  199,  197,  312,  199,  199,  199,  311,  146,  201,
      201,  201,  310,  146,  197,  202,  202,  202,  309,  197,
      249,  249,  249,  250,  250,  250,  202,  308,  202,  307,
      306,  305,  304,  303,  250,  302,  250,  301,  300,  293,

      202,  291,  290,  286,  285,  202,  284,  283,  250,  282,
      281,  280,  279,  250,  348,  348,  348,  348,  348,  349,
      349,  349,  349,  349,  350,  350,  278,  350,  350,  351,
      351,  352,  277,  352,  352,  352,  353,  353,  353,  353,
      353,  354,  354,  354,  354,  354,  276,  274,  273,  271,
      270,  269,  268,  267,  266,  264,  263,  262,  261,  260,
      258,  257,  256,  255,  254,  248,  247,  246,  245,  244,
      243,  241,  240,  239,  237,  236,  235,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  219,  218,
      215,  214,  213,  212,  211,  210,  207,  195,  194,  192,

      191,  190,  189,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  167,  165,  163,  162,  161,  160,  159,  158,
      157,  155,  154,  153,  152,  151,  150,  139,  137,  132,
      131,  130,  129,  127,  124,  121,  120,  119,  118,  115,
      113,  111,  110,  109,  107,  106,  105,  104,  103,  102,
      101,   99,   98,   97,   96,   95,   94,   93,   90,   86,
       78,   77,   75,   64,   63,   51,   50,   49,   46,   44,
       43,   41,   35,   34,   28,   17,   14,   12,   11,    9,
        5,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[113] =
    {   0,
1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "clex.l"
/*
 * Lydia Engerbretson
 * Fall 2017
 * ideas and some code snippets adapted from https://github.com/andschwa/partial-cpp-compiler
 * ideas and some code snippets adapted from https://github.com/park2331
 *
 */

#line 23 "clex.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

#include "token.h"
#include "ytab.h"

extern int yychar;
FILE *saved_yyin;
extern struct tokenlist *YYTOKENLIST; 
extern struct token *YYTOKEN; 
extern char* curr_filename; 
extern filenodeptr file_stack;
extern char* filetext;  
extern int include; 

void add_token(int category); 
void lexerr(char *s);
void handle_include(char *s);

/* #define DEBUG */

int errors;
int included_iostream = 0;

#line 755 "lex.yy.c"

#define INITIAL 0
#define INCLUDE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 51 "clex.l"


#line 946 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 492 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 53 "clex.l"
{ yylineno++; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 55 "clex.l"
{ /* eat whitespace */ }
	YY_BREAK
case 3:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 57 "clex.l"
{ /* eat comment */}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 59 "clex.l"
{ /* eat comment */} // adapted from http://www2.cs.uidaho.edu/~jeffery/courses/445/lecture.html#5
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "clex.l"
{BEGIN(INCLUDE);}
	YY_BREAK

case 6:
YY_RULE_SETUP
#line 63 "clex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 "clex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "clex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 "clex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "clex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "clex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 69 "clex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 70 "clex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 71 "clex.l"
{ handle_include(yytext); BEGIN(INITIAL); }
	YY_BREAK

case 15:
YY_RULE_SETUP
#line 74 "clex.l"
{ add_token(AUTO); return AUTO; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 75 "clex.l"
{ add_token(BOOL); return BOOL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 "clex.l"
{ add_token(BREAK); return BREAK; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 77 "clex.l"
{ add_token(CASE); return CASE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "clex.l"
{ add_token(CHAR); return CHAR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 79 "clex.l"
{ add_token(CLASS); return CLASS; } //  added
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 80 "clex.l"
{ add_token(CONST); return CONST; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 81 "clex.l"
{ add_token(CONTINUE); return CONTINUE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 82 "clex.l"
{ add_token(DEFAULT); return DEFAULT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 83 "clex.l"
{ add_token(DELETE); return DELETE; } //  added
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 84 "clex.l"
{ add_token(DO); return DO; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 85 "clex.l"
{ add_token(DOUBLE); return DOUBLE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "clex.l"
{ add_token(ELSE); return ELSE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 "clex.l"
{ add_token(ENUM); return ENUM; } 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 "clex.l"
{ add_token(EXTERN); return EXTERN; } 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "clex.l"
{ add_token(FLOAT); return FLOAT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "clex.l"
{ add_token(FOR); return FOR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "clex.l"
{ add_token(GOTO); return GOTO; } 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "clex.l"
{ add_token(IF); return IF; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "clex.l"
{ add_token(INT); return INT; } 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "clex.l"
{ add_token(LONG); return LONG; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "clex.l"
{ add_token(NEW); return NEW; } //  added 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 96 "clex.l"
{ add_token(PRIVATE); return PRIVATE; } //  added
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 97 "clex.l"
{ add_token(PROTECTED); return PROTECTED; } //  added
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 98 "clex.l"
{ add_token(PUBLIC); return PUBLIC; } //  added
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 99 "clex.l"
{ add_token(REGISTER); return REGISTER; } 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "clex.l"
{ add_token(RETURN); return RETURN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 101 "clex.l"
{ add_token(SHORT); return SHORT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 102 "clex.l"
{ add_token(SIGNED); return SIGNED; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 103 "clex.l"
{ add_token(SIZEOF); return SIZEOF; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 104 "clex.l"
{ add_token(STATIC); return STATIC; } 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "clex.l"
{ add_token(STRUCT); return STRUCT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 106 "clex.l"
{ add_token(SWITCH); return SWITCH; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 107 "clex.l"
{ add_token(TYPEDEF); return TYPEDEF; } 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 108 "clex.l"
{ add_token(UNION); return UNION; } 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 109 "clex.l"
{ add_token(THIS); return THIS; } 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 110 "clex.l"
{ add_token(TRUE); return TRUE; } //  added 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 111 "clex.l"
{ add_token(UNSIGNED); return UNSIGNED; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 112 "clex.l"
{ add_token(VOID); return VOID; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 113 "clex.l"
{ add_token(VOLATILE); return VOLATILE; } 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 114 "clex.l"
{ add_token(WHILE); return WHILE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 116 "clex.l"
{ add_token(IDENTIFIER); return IDENTIFIER; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "clex.l"
{ lexerr("Hex not supported\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "clex.l"
{ lexerr("Octal not supported\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 122 "clex.l"
{ add_token(ICON); return ICON; }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 123 "clex.l"
{ add_token(CCON); return CCON;  }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 124 "clex.l"
{ add_token(FCON); return FCON;  }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 "clex.l"
{ add_token(FCON); return FCON;  }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "clex.l"
{ add_token(FCON); return FCON;  }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 127 "clex.l"
{ add_token(STRING); return STRING; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 130 "clex.l"
{ add_token(SRASN); return SRASN;  }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 131 "clex.l"
{ add_token(SLASN); return SLASN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 132 "clex.l"
{ add_token(PLASN); return PLASN;  }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 133 "clex.l"
{ add_token(MIASN); return MIASN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 134 "clex.l"
{ add_token(MUASN); return MUASN;  }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 135 "clex.l"
{ add_token(DIASN); return DIASN;  }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 136 "clex.l"
{ add_token(MOASN); return MOASN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 137 "clex.l"
{ add_token(ANASN); return ANASN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 138 "clex.l"
{ add_token(ERASN); return ERASN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 139 "clex.l"
{ add_token(ORASN); return ORASN;  }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 140 "clex.l"
{ add_token(SHR); return SHR;  }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 141 "clex.l"
{ add_token(SHL); return SHL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 142 "clex.l"
{ add_token(INCOP); return INCOP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 143 "clex.l"
{ add_token(DECOP); return DECOP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 144 "clex.l"
{ add_token(FOLLOW); return FOLLOW; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 145 "clex.l"
{ add_token(FOLLOWPTR); return FOLLOWPTR;} // just added
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 146 "clex.l"
{ add_token(ANDAND); return ANDAND;  }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 147 "clex.l"
{ add_token(OROR); return OROR; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 148 "clex.l"
{ add_token(LE); return LE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 149 "clex.l"
{ add_token(GE); return GE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 150 "clex.l"
{ add_token(EQ); return EQ; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 151 "clex.l"
{ add_token(NE); return NE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 152 "clex.l"
{ add_token(SM); return SM; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 153 "clex.l"
{ add_token(LC); return LC; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 154 "clex.l"
{ add_token(RC); return RC; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 155 "clex.l"
{ add_token(CM); return CM; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 156 "clex.l"
{ add_token(COLON); return COLON; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 157 "clex.l"
{ add_token(ASN); return ASN; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 158 "clex.l"
{ add_token(LP); return LP; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 159 "clex.l"
{ add_token(RP); return RP; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 160 "clex.l"
{ add_token(LB); return LB; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 161 "clex.l"
{ add_token(RB); return RB; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 162 "clex.l"
{ add_token(DOT); return DOT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 163 "clex.l"
{ add_token(AND); return AND; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 164 "clex.l"
{ add_token(BANG); return BANG; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 165 "clex.l"
{ add_token(NOT); return NOT; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 166 "clex.l"
{ add_token(MINUS); return MINUS; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 167 "clex.l"
{ add_token(PLUS); return PLUS; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 168 "clex.l"
{ add_token(MUL); return MUL; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 169 "clex.l"
{ add_token(DIV); return DIV; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 170 "clex.l"
{ add_token(MOD); return MOD; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 171 "clex.l"
{ add_token(LT); return LT; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 172 "clex.l"
{ add_token(GT); return GT; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 173 "clex.l"
{ add_token(ER); return ER; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 174 "clex.l"
{ add_token(OR); return OR; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 175 "clex.l"
{ add_token(QUEST); return QUEST; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 176 "clex.l"
{ lexerr(yytext); return; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INCLUDE):
#line 177 "clex.l"
{
  yypop_buffer_state();
  pop_file_node(&file_stack);
  if (file_stack == NULL) {
    yyterminate();    
  }

  yylineno = 1;
  
  if (!YY_CURRENT_BUFFER) {
    yyterminate();
  } 
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 191 "clex.l"
ECHO;
	YY_BREAK
#line 1627 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 347);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 191 "clex.l"



void lexerr(char *s)
{
	errors++;

	fprintf(stderr, "%s: lexical error", s);

	/* to do: add mechanism for reporting file name and line number */
   
	fprintf(stderr, ", token = \"%s\"\n", yytext);
	fprintf(stderr, ", filename = \"%s\"\n", curr_filename);
	fprintf(stderr, ", line number = \"%d\"\n", yylineno);
}

void add_token(int category)
{
   // global YYTOKEN
    filetext = file_stack->filename;
   	YYTOKEN = create_token(category, yytext, yylineno, filetext);  // used to be curr_filename
	add_token_to_list(YYTOKEN);
   
  	
}
/*
 * Return 1 if done, 0 if yyin points at more input
 */
int yywrap()
{
   return 1;
}

void handle_include(char *s)
{
  // help from Clinton Jeffery
  FILE *include_buffer;
  YY_BUFFER_STATE incl_state;

  char *fname = malloc(strlen(yytext)+1-strlen("#include \"\""));
  fname = strchr(yytext, '\"')+1;
  fname[strlen(fname)-1] = '\0';
  printf("%s\n",fname);
  yyin = fopen(fname,"r");
  if(yyin == NULL)
  {
     printf("File %s is not recognized. \n", fname); 
	 return; 
  }
  push_file_node(&file_stack, fname);
  yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE));
   
}

